Elastic Stack

diff --git a/overlay/opt/kibana/bin/kibana b/overlay/opt/kibana/bin/kibana
--- a/overlay/opt/kibana/bin/kibana
+++ b/overlay/opt/kibana/bin/kibana
@@ -13,7 +13,12 @@ while [ -h "$SCRIPT" ] ; do
   fi
 done
 
-DIR=$(dirname "${SCRIPT}")/..
-SERVER=${DIR}/src/bin/kibana.js
+DIR="$(dirname "${SCRIPT}")/.."
+NODE="node"
+test -x "$NODE" || NODE=$(which node)
+if [ ! -x "$NODE" ]; then
+  echo "unable to find usable node.js executable."
+  exit 1
+fi
 
-CONFIG_PATH="${DIR}/config/kibana.yml" NODE_ENV="production" exec "node" ${SERVER} ${@}
+exec "${NODE}" $NODE_OPTIONS --no-warnings "${DIR}/src/cli" ${@}
